name: Run MERN App

on:
  push:
    branches:
      - main

jobs:
  print-readme-first-line:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Print the first line of the README.md file
        run: head -n 1 README.md

  run-frontend:
    runs-on: ubuntu-latest
    needs: run-backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd frontend
          npm ci
          npm run build

  run-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd frontend
          npm ci
          npm run build
